/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as HeroesIndexRouteImport } from './routes/heroes/index'
import { Route as TabTabNumberRouteImport } from './routes/tab/$tabNumber'
import { Route as SShareSlugRouteImport } from './routes/s/$shareSlug'
import { Route as PlayersAccountIdRouteImport } from './routes/players/$accountId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/heroes/',
  path: '/heroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabTabNumberRoute = TabTabNumberRouteImport.update({
  id: '/tab/$tabNumber',
  path: '/tab/$tabNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const SShareSlugRoute = SShareSlugRouteImport.update({
  id: '/s/$shareSlug',
  path: '/s/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersAccountIdRoute = PlayersAccountIdRouteImport.update({
  id: '/players/$accountId',
  path: '/players/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/s/$shareSlug': typeof SShareSlugRoute
  '/tab/$tabNumber': typeof TabTabNumberRoute
  '/heroes/': typeof HeroesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/s/$shareSlug': typeof SShareSlugRoute
  '/tab/$tabNumber': typeof TabTabNumberRoute
  '/heroes': typeof HeroesIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/s/$shareSlug': typeof SShareSlugRoute
  '/tab/$tabNumber': typeof TabTabNumberRoute
  '/heroes/': typeof HeroesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/players/$accountId'
    | '/s/$shareSlug'
    | '/tab/$tabNumber'
    | '/heroes/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/players/$accountId'
    | '/s/$shareSlug'
    | '/tab/$tabNumber'
    | '/heroes'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/players/$accountId'
    | '/s/$shareSlug'
    | '/tab/$tabNumber'
    | '/heroes/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayersAccountIdRoute: typeof PlayersAccountIdRoute
  SShareSlugRoute: typeof SShareSlugRoute
  TabTabNumberRoute: typeof TabTabNumberRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tab/$tabNumber': {
      id: '/tab/$tabNumber'
      path: '/tab/$tabNumber'
      fullPath: '/tab/$tabNumber'
      preLoaderRoute: typeof TabTabNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$shareSlug': {
      id: '/s/$shareSlug'
      path: '/s/$shareSlug'
      fullPath: '/s/$shareSlug'
      preLoaderRoute: typeof SShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$accountId': {
      id: '/players/$accountId'
      path: '/players/$accountId'
      fullPath: '/players/$accountId'
      preLoaderRoute: typeof PlayersAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayersAccountIdRoute: PlayersAccountIdRoute,
  SShareSlugRoute: SShareSlugRoute,
  TabTabNumberRoute: TabTabNumberRoute,
  HeroesIndexRoute: HeroesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
