/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as HeroesIndexRouteImport } from './routes/heroes/index'
import { Route as PlayersAccountIdRouteImport } from './routes/players/$accountId'
import { Route as HeroesSlugRouteImport } from './routes/heroes/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesIndexRoute = HeroesIndexRouteImport.update({
  id: '/heroes/',
  path: '/heroes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersAccountIdRoute = PlayersAccountIdRouteImport.update({
  id: '/players/$accountId',
  path: '/players/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroesSlugRoute = HeroesSlugRouteImport.update({
  id: '/heroes/$slug',
  path: '/heroes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/heroes/': typeof HeroesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/heroes': typeof HeroesIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/heroes/$slug': typeof HeroesSlugRoute
  '/players/$accountId': typeof PlayersAccountIdRoute
  '/heroes/': typeof HeroesIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/heroes/$slug'
    | '/players/$accountId'
    | '/heroes/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/heroes/$slug' | '/players/$accountId' | '/heroes' | '/players'
  id:
    | '__root__'
    | '/'
    | '/heroes/$slug'
    | '/players/$accountId'
    | '/heroes/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroesSlugRoute: typeof HeroesSlugRoute
  PlayersAccountIdRoute: typeof PlayersAccountIdRoute
  HeroesIndexRoute: typeof HeroesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/': {
      id: '/heroes/'
      path: '/heroes'
      fullPath: '/heroes/'
      preLoaderRoute: typeof HeroesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$accountId': {
      id: '/players/$accountId'
      path: '/players/$accountId'
      fullPath: '/players/$accountId'
      preLoaderRoute: typeof PlayersAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heroes/$slug': {
      id: '/heroes/$slug'
      path: '/heroes/$slug'
      fullPath: '/heroes/$slug'
      preLoaderRoute: typeof HeroesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroesSlugRoute: HeroesSlugRoute,
  PlayersAccountIdRoute: PlayersAccountIdRoute,
  HeroesIndexRoute: HeroesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
